### ISSUE TITLE
Before/after Add to Cart button elements

### ISSUE THREAD

**Issue by cqrmskgiub** [somewherewarm/woocommerce-product-bundles-top-add-to-cart-button#1]
I needed to modify this plugin. With the modifications below, things that are added just before or after the Add to Cart button by other plugins also show up (subscribe all the things, WC extra product options, etc). Thought it would be helpful to share.

	/**
	 * Show extra add-to-cart button section.
	 */
	public static function top_add_to_cart() {

		global $product;

		/*** MANUALLY ADDED FOR ABOVE ADD TO CART BUTTON ELEMENTS TO SHOW ***/
		do_action( 'woocommerce_before_add_to_cart_button' );		
		/********************************************************************/	
		
		if ( is_a( $product, 'WC_Product_Bundle' ) ) {

			$elements      = apply_filters( 'woocommerce_bundles_top_add_to_cart_elements', array( 'error', 'availability', 'button' ), $product );
			$elements_html = '';

			foreach ( $elements as $el ) {
				$elements_html .= '<div class="bundle_' . $el . '"' . ( 'error' === $el ? ' style="display:none"' : '' ) . '></div>';
			}

			if ( ! empty( $elements_html ) ) {
				echo '<form method="post" class="cart bundle_form bundle_form_top"><div class="bundle_wrap">' . $elements_html . '</div></form>';
			}
		}

		/*** MANUALLY ADDED FOR BELOW ADD TO CART BUTTON ELEMENTS TO SHOW ***/
		do_action( 'woocommerce_before_add_to_cart_button' );		
		/********************************************************************/

	}

**Comment by cqrmskgiub** [comment]
Oops! Need to move the added code to within the if statement:

	/**
	 * Show extra add-to-cart button section.
	 */
	public static function top_add_to_cart() {

		global $product;

		
		if ( is_a( $product, 'WC_Product_Bundle' ) ) {

		/***************** MANUALLY ADDED TO ABOVE CART ELEMENTS TO SHOW *****************/
		do_action( 'woocommerce_before_add_to_cart_button' );		
		/*********************************************************************************/	

			$elements      = apply_filters( 'woocommerce_bundles_top_add_to_cart_elements', array( 'error', 'availability', 'button' ), $product );
			$elements_html = '';

			foreach ( $elements as $el ) {
				$elements_html .= '<div class="bundle_' . $el . '"' . ( 'error' === $el ? ' style="display:none"' : '' ) . '></div>';
			}

			if ( ! empty( $elements_html ) ) {
				echo '<form method="post" class="cart bundle_form bundle_form_top"><div class="bundle_wrap">' . $elements_html . '</div></form>';
			}

		/***************** MANUALLY ADDED TO BELOW CART ELEMENTS TO SHOW *****************/
		do_action( 'woocommerce_after_add_to_cart_button' );		
		/*********************************************************************************/	

		}
	}

**Comment by manospsyx** [comment]
@cqrmskgiub thanks for the suggestion! 

However, form elements added there will not be posted -- remember this is not a replacement for the actual add-to-cart button. Therefore I'm a bit skeptical about showing "stuff" there that needs to be posted to work.
