### ISSUE TITLE
Issues when moving add to cart button on all product types

### ISSUE THREAD

**Issue by JKNN** [somewherewarm/woocommerce-product-bundles-top-add-to-cart-button#2]
Hi guys. Great add-on.

I use the following snippet in my functions.php to move the add to cart button on all products:
```
remove_action('woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30);
add_action('woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 15);
```

However, when this is used, your add-on seems to be not working.

Instead it shows two add to cart buttons at the bottom of product bundles like shown here:
![image](https://user-images.githubusercontent.com/4228900/56201534-5cf1c500-6041-11e9-9c4f-d8ba642a8ad2.png)

Is there a workaround for this? I really want the add to cart button on top of my product bundles. But I still need to have the add to cart button above short description on all products.

**Comment by manospsyx** [comment]
Hey @JKNN -- could you please open an issue via your WooCommerce.com account dashboard? We'll be happy to look into details there!
